baseURL = "http://example.org/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Rubi Thought"
theme = "anatole"
enableEmoji = true

[params]
title = "Rubi Thought"
author = "Rubi"
description = "Bingung harus di isi apa bagian ini"
profilePicture = "images/profile.jpg"
keywords = "codenoid,jihantoro"

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/codenoid"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "twitter"
url = "https://www.twitter.com/codenoid_"

## Menu items

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  weight = 400
  identifier = "contact"
  url = "/contact/"